{{- if .Values.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-svtrest
  labels:
    app: svtrest-simulator

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: svtrest-simulator

  template:
    metadata:
      labels:
        app: svtrest-simulator
    spec:
      containers:
        - name: svtrest
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-svtrest-config

{{- end }}